name: SmokeTest

on: [push]

jobs:
  smoke-test:
    strategy:
      matrix:
        go:
          - 1.15

    name: SmokeTest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Run wasataro on background
        run: ./cmd/wasataro/wasataro &

      - run: curl -v localhost:3000
